name: Pull Request

on:
  pull_request:
    branches:
      - "develop"
      - "master"

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run Detekt
        run: cd app && bash ./gradlew detekt
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Test Report
        run: cd app && bash ./gradlew createTestReport
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/jacoco/jacocoTestReport.xml
          fail_ci_if_error: true
          verbose: true
